---
fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v2.1.0"
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-json
      - id: check-yaml
      - id: debug-statements
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: double-quote-string-fixer
      - id: end-of-file-fixer
      - id: flake8
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: "v2.3.1"
    hooks:
      - id: pylint
  - repo: https://github.com/pre-commit/mirrors-yapf
    rev: "v0.26.0"
    hooks:
      - id: yapf
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.670"
    hooks:
      - id: mypy
  - repo: https://github.com/ansible/ansible-lint
    rev: "v4.1.0"
    hooks:
      - id: ansible-lint
