---
- name: deploy application
  hosts: v2
  tasks:
    - name: clone repo
      become: yes
      become_user: "{{ app_user }}"
      git:
        repo: https://github.com/585-software/rocdev.git
        dest: "{{ clone_dir }}"

    - name: enable application
      become: yes
      become_user: root
      systemd:
        name: rocdev
        enabled: yes
        daemon_reload: yes

    - name: restart application
      become: yes
      become_user: root
      systemd:
        name: rocdev
        state: restarted
