---
- name: base setup
  hosts: web
  become: yes
  roles:
    - role: users

- name: web setup
  hosts: web
  become: yes
  roles:
    - role: web
      site_dns: rocdev.org
      site_admin: admin@rocdev.org
    - role: database
    - role: application
