---
- name: install erlang deb
  apt:
    deb: https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb

- name: install application packages
  apt:
    update_cache: yes
    name: "{{ item }}"
  with_items:
    - esl-erlang
    - elixir
    - nodejs
    - npm

- name: create application user
  user:
    name: "{{ app_user }}"
    shell: /bin/bash

- name: install python pexpect module
  apt:
    name: python-pexpect

- name: install hex
  become_user: "{{ app_user }}"
  command: mix local.hex --force
  args:
    creates: "/home/{{ app_user }}/.mix/archives/hex-*/hex-*/.elixir"
