---
- name: allow application user services to linger
  command: loginctl enable-linger {{ app_user }}
  args:
    creates: /var/lib/systemd/linger/{{ app_user }}

- name: set environment variables for unit
  become_user: "{{ app_user }}"
  template:
    src: rocdev.conf
    dest: /home/{{ app_user }}/rocdev.conf

- name: install systemd unit
  template:
    src: rocdev.service
    dest: /etc/systemd/system/rocdev.service
