---
all:
  vars:
    admins:
      - geowa4
    app_user: rocdev
    public_keys:
      geowa4: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKv0qAuJaZE43zqCjd8TOwC+58QTiy9LfkYlVDeAQhtr
    rocdev_secret_key_base: "{{ lookup('env', 'ROCDEV_SECRET_KEY_BASE') }}"
    slack_invite_api_base: "{{ lookup('env', 'SLACK_INVITE_API_BASE') }}"
    slack_invite_api_token: "{{ lookup('env', 'SLACK_INVITE_API_TOKEN') }}"
    slack_api_base: "{{ lookup('env', 'SLACK_API_BASE') }}"
    slack_api_token: "{{ lookup('env', 'SLACK_API_TOKEN') }}"
    meetup_api_base: "{{ lookup('env', 'MEETUP_API_BASE') }}"
    sparkpost_api_key: "{{ lookup('env', 'SPARKPOST_API_KEY') }}"
    clone_dir: /home/{{ app_user }}/rocdev
    app_dir: "{{ clone_dir }}/app"
  children:
    web:
