---
all:
  vars:
    app_user: rocdev
    rocdev_secret_key_base: "{{ lookup('env', 'ROCDEV_SECRET_KEY_BASE') }}"
    slack_invite_api_base: "{{ lookup('env', 'SLACK_INVITE_API_BASE') }}"
    slack_invite_api_token: "{{ lookup('env', 'SLACK_INVITE_API_TOKEN') }}"
    slack_api_base: "{{ lookup('env', 'SLACK_API_BASE') }}"
    slack_api_token: "{{ lookup('env', 'SLACK_API_TOKEN') }}"
    meetup_api_base: "{{ lookup('env', 'MEETUP_API_BASE') }}"
    sparkpost_api_key: "{{ lookup('env', 'SPARKPOST_API_KEY') }}"
    clone_dir: /home/{{ app_user }}/rocdev
    web_dir: "{{ clone_dir }}/web"
  children:
    web:
