---
- name: set environment variables for unit
  become_user: "{{ app_user }}"
  template:
    src: rocdev.conf
    dest: /home/{{ app_user }}/rocdev.conf

- name: install systemd unit
  template:
    src: rocdev.service
    dest: /etc/systemd/system/rocdev.service
